"""
All outbound copy lives here — first email, follow-up, opener prompt.
Every sender script (list_send, send/personalize, followup) imports from this
file, so changing the pitch means editing ONE place.

Product: Quelp — an AI call agent for B2B sales teams.
Audience: sales leaders, AEs, SEs at 20–200 person B2B SaaS.
Rules: buyer's pain first, product described by what it does on the call,
no stack/vendor names, no invented customers or stats, "I'm building" (pre-launch).
"""

import hashlib

from config import SENDER_NAME, SENDER_SITE, SENDER_TITLE

# ---------------------------------------------------------------------------
# First email
# ---------------------------------------------------------------------------

# Several subjects and closings, so a day's sends are not byte-identical.
# The variant is chosen from a hash of the recipient's address, NOT at random:
# it must come out the same in the preview and in the live send, and the same
# on a re-run, or you would preview one email and send another.

SUBJECTS = [
    "the \"let me get back to you\" moment",
    "when your rep can't answer on the call",
    "the pause mid-call that costs the deal",
]

# First entry stays importable as pitch.SUBJECT for older callers.
SUBJECT = SUBJECTS[0]

PRODUCT = (
    "I'm building Quelp, an AI agent that sits in on your sales calls. Before the "
    "call it loads the account: past commitments, open objections, the CRM record "
    "and the latest email. During the call it answers the rep's questions in a side "
    "panel from your docs, playbook and CRM, and says \"I don't have that\" instead "
    "of guessing. After the call it records what was promised, so the next call "
    "picks up where the last one ended."
)

CLOSINGS = [
    "Happy to set it up on a few of your real calls so you can see whether it "
    "actually helps. Free, and no work on your side. Worth 15 minutes?",

    "If it's worth a look, I'll set it up on a couple of your live calls and you "
    "can judge it from there. No cost, nothing to configure. Worth 15 minutes?",

    "I can have it running on your next few calls with nothing needed from your "
    "side, so you can see whether it earns its place. Worth 15 minutes?",
]

BODY = """\
Hi {first_name},

{opener}

{product}

{closing}

{sender_name}
{sender_title} · {sender_site}

{opt_out}"""

# ---------------------------------------------------------------------------
# Follow-up (sent once, in the same thread, only if there's been no reply)
# ---------------------------------------------------------------------------

FOLLOWUP_BODY = """\
Hi {first_name},

Bumping this once. If your reps ever get stuck mid-call on a question someone else in the company could answer, that's the gap Quelp closes.

Happy to show it on a 15-minute call. If it's not a fit, a one-word "no" is fine and I'll stop here.

{sender_name}"""

# ---------------------------------------------------------------------------
# Opt-out line (appended to every first email)
# ---------------------------------------------------------------------------

OPT_OUT = "P.S. Not relevant? Reply \"no\" and I won't email again."

# ---------------------------------------------------------------------------
# Opener — one personalised line, generated by the LLM
# ---------------------------------------------------------------------------

OPENER_SYSTEM = (
    "You write the first line of a cold email from a founder to someone on a "
    "B2B sales team. Plain, direct, no flattery, no exclamation marks, no emojis. "
    "Never invent facts about the person or company (no funding, launches, "
    "growth, hiring, awards, customers). Only use what you are given. "
    "Never mention any product, AI or the sender's company. "
    "Return ONE sentence, max 22 words, no quotes."
)


def opener_prompt(first_name: str, title: str, company: str,
                  industry: str = "", page_text: str = "") -> str:
    """User prompt for the opener. page_text is optional homepage context."""
    parts = [
        f"Recipient: {first_name or 'unknown'}, {title or 'unknown title'} at {company or 'their company'}.",
        f"Industry: {industry or 'B2B software'}.",
    ]
    if page_text:
        parts.append(f"What the company does (from its homepage): {page_text[:600]}")
    parts.append(
        "Write a first line that connects their role to the moment on a sales call "
        "when a buyer asks something the rep can't answer on the spot. "
        "If the title is a sales leader, frame it around their team; if it's an AE "
        "or SE, frame it around their own calls."
    )
    return "\n".join(parts)


def fallback_opener(title: str, company: str) -> str:
    """
    Used when there's no LLM key or the call fails. Safe, factual, generic.

    This line also has to STATE THE PROBLEM: the body goes straight from the
    opener into the product, so an opener that only says hello leaves the
    email with no reason for the reader to care.
    """
    t = (title or "").lower()
    # Account managers/executives are individual contributors, not team leads.
    ic = any(k in t for k in ("account manager", "account executive", "engineer"))
    leader = not ic and any(k in t for k in (
        "head", "vp", "vice president", "director", "chief", "cro",
        "sales manager", "team lead", "founder", "ceo"))
    if leader:
        return ("When one of your reps can't answer a buyer's question on the call, "
                "the deal cools while they chase the answer internally.")
    return ("When a buyer asks something you can't answer on the call, the deal cools "
            "while you chase the answer internally.")


# ---------------------------------------------------------------------------
# Assembly helpers
# ---------------------------------------------------------------------------

def _variant(key: str, count: int) -> int:
    """Stable index from the recipient's address — same answer every run."""
    if not key:
        return 0
    return int(hashlib.sha1(key.strip().lower().encode()).hexdigest(), 16) % count


def is_current_subject(subject: str) -> bool:
    """
    True if this subject belongs to the CURRENT campaign. followup.py uses it
    to avoid nudging someone in a thread from an older pitch — a check that
    used to compare against one fixed subject.
    """
    def norm(value: str) -> str:
        value = str(value).strip()
        while value.lower().startswith("re:"):
            value = value[3:].strip()
        return value.lower()

    return norm(subject) in {norm(s) for s in SUBJECTS}


def render_first_email(first_name: str, opener: str, key: str = "") -> tuple[str, str]:
    """
    key is the recipient's email address; it picks the subject and closing so
    a day's sends are not byte-identical. Omitting it gives the first variant,
    which keeps previews and spam checks deterministic.
    """
    body = BODY.format(
        first_name=first_name or "there",
        opener=opener.strip(),
        product=PRODUCT,
        closing=CLOSINGS[_variant(key, len(CLOSINGS))],
        sender_name=SENDER_NAME,
        sender_title=SENDER_TITLE,
        sender_site=SENDER_SITE,
        opt_out=OPT_OUT,
    )
    return SUBJECTS[_variant(key, len(SUBJECTS))], body


def render_followup(first_name: str) -> str:
    return FOLLOWUP_BODY.format(
        first_name=first_name or "there",
        sender_name=SENDER_NAME,
    )
